server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          # git上的仓库地址
          uri: https://github.com/yysimple/microservicecloud-config.git
